### ISSUE TITLE
Other lists

### ISSUE THREAD

**Issue by YerkoPalma** [mafintosh/awesome-p2p#1]
There are already a couple of awesome p2p lists.

- https://github.com/steve-vincent/awesome-decentralized
- https://github.com/kgryte/awesome-peer-to-peer
- https://github.com/retrohacker/awesome-p2p

I'm just pointing it in case that you were not aware of those lists, you can merge resources or just ignore them :)
Also, feel free to close this after you read it.

**Comment by mafintosh** [comment]
Thanks!! This one is *just* for docs/articles/papers and only about the tech aspect. Also heavily curated by me

**Comment by YerkoPalma** [comment]
Cool, closing then :smile:
